version: "3"
services:
  postgres:
    container_name: postgres
    image: "postgres:15.0-alpine"
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - "${PGPORT}:${PGPORT}"
    # volumes:
    #   - ./server/config:/postgres
    restart: unless-stopped
  server:
    container_name: server
    image: server
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: "./server"
    environment:
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
    ports:
      - "4000:4000"
    links:
      - client
  client:
    container_name: client
    image: client
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "3000:3000"